#!/usr/bin/python3
#
# -*- coding: UTF-8 -*-
#
# Copyright 2016 Diego "Ocelotl" Hurtado Pimentel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This module implements a commit message checker git hook."""

from __future__ import unicode_literals, absolute_import
from __future__ import print_function, division

from commit_message import check_commit_message
from sys import argv, exit
from re import match, DOTALL


with open(argv[1]) as commit_message_file:
    commit_message = commit_message_file.read()

commit_message = match(r'^.*?(?=\n#)', commit_message, DOTALL).group()

if check_commit_message(commit_message):
    exit(0)

print('Unable to commit, wrong commit message.')
exit(1)
